
name: GPT-3-DE
# run-name: Compile and push PDF File             !outdated
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      - name: System
        run: |
          echo "User: ${{ github.actor }}"
          echo "Trigger: ${{ github.event_name }}"
          echo "OS: ${{ runner.os }}"
          echo "Branch: ${{ github.repository }}:${{ github.ref }}"
           
      - name: Compile Latex File
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./GPT-3
          root_file: ./main.tex

      - name: Rename PDF
        run: |
          mv ./GPT-3/EN/main.pdf Proseminar_ProbaData_GPT3_DE.pdf

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Proseminar_ProbaData_GPT3_DE
          path: Proseminar_ProbaData_GPT3_DE.pdf

      - name: Load Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Python FTP Handler
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_PWD: ${{ secrets.FTP_PWD }}
          FTP_USER: ${{ secrets.FTP_USER }}
        run: python upload.py Proseminar_ProbaData_GPT3_DE.pdf

      - name: Git Clean
        run: git clean -fX
      
      - name: Status
        run: echo "This job's status is ${{ job.status }}."